yiisoft/var-dumper

src/VarDumper.php
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |
> Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility. - https://www.php-fig.org/psr/psr-2/#42-properties
=> Follow PSR-2 coding style

composer.json, src/VarDumper.php, tests/VarDumperTest.php
=> Add json vardump

README.md, composer.json, psalm.xml, src/VarDumper.php
| New feature?  | ✔️/❌
| Breaks BC?    |
| Fixed issues  |
=> Adopt Psalm

.github/workflows/build.yml, infection.json.dist, src/VarDumper.php, tests/VarDumperTest.php
Added some test cases
Added forgotten import
=> Enhancements

src/VarDumper.php, tests/VarDumperTest.php
=> Fixed #17, added test and made some refactoring

tests/VarDumperTest.php
=> Added extra test case

tests/VarDumperTest.php
=> Tests refactoring

.github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, README.md
=> Update pipelines and README.md

src/VarDumper.php, tests/VarDumperTest.php
| Breaks BC?    | ✔️
* Static modifier will be showed when closure is static in any dump methods
* Added extra test cases
* Cosmetic refactoring
=> Regular enhancements :)

src/ClosureExporter.php, src/VarDumper.php
=> Extract closure exporter

src/ClosureExporter.php, tests/ClosureExporterTest.php
=> Extra tests for ClosureExporter

CHANGELOG.md, README.md, composer.json, phpunit.xml.dist, src/ClosureExporter.php, src/VarDumper.php
=> Improve readme + Minor beautify of code + Update dev dependencies

psalm.xml, src/ClosureExporter.php, src/UseStatementParser.php, src/VarDumper.php
=> Fix Psalm errors

CHANGELOG.md, README.md, infection.json.dist, src/VarDumper.php, src/functions.php, tests/TestAsset/DummyJsonSerializableWithClosure.php, tests/VarDumperTest.php
=> Fix dump functions and readme, improve VarDumper::export()

CHANGELOG.md, src/VarDumper.php
=> Remove unused $objects property from VarDumper

CHANGELOG.md, src/ClosureExporter.php, tests/ClosureExporterTest.php
| Fixed issues  | Affects https://github.com/yiisoft/yii-debug/
=> Issue exporting closures with use under PHP 8

CHANGELOG.md, src/functions.php
=> Add line break in dump functions for highlight mode

CHANGELOG.md, src/ClosureExporter.php, tests/ClosureExporterTest.php
=> Fix export of static method call to ClosureExporter

CHANGELOG.md, README.md, src/ClosureExporter.php, src/VarDumper.php, tests/TestAsset/DummyClass.php, tests/VarDumperTest.php
=> Add export objects with closures

CHANGELOG.md, README.md, src/VarDumper.php, tests/VarDumperTest.php
=> Add json export

src/VarDumper.php
=> Revert "Fix json serialization"

composer.json
=> Improve composer description

.github/workflows/composer-require-checker.yml, CHANGELOG.md, composer.json, tests/VarDumperTest.php
Added composer-require-checker according to https://github.com/yiisoft/actions/pull/9
=> [Batch] Add composer-require-checker CI

.github/workflows/rector.yml, CHANGELOG.md, composer.json, rector.php, src/ClosureExporter.php, src/VarDumper.php, src/functions.php, tests/TestAsset/DummyArrayableWithClosure.php, tests/TestAsset/DummyJsonSerializableWithClosure.php, tests/TestAsset/DummyStringableWithClosure.php, tests/UseStatementParserTest.php, tests/VarDumperTest.php
Added rector/rector to CI and composer.json. Mass creation refers to https://github.com/yiisoft/yii-dev-tool/pull/232
=> Add rector and apply suggestions

.github/workflows/bc.yml, .github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mutation.yml, .github/workflows/rector.yml, .github/workflows/static.yml, psalm.xml, rector.php
=> Improve CI

.github/workflows/build.yml, CHANGELOG.md, src/Handler/EchoHandler.php, tests/Handler/EchoHandlerTest.php, tests/VarDumperTest.php
=> Improve resulting HTML of syntax highlighting in `EchoHandler`
